name: Xcode

on: [push]

jobs:
  xcode-12-4-ios:
    name: "Xcode 12.4, iOS"
    runs-on: macOS-10.15
    strategy:
      matrix:
        env:
          - RUNTIME="iOS 10.0" DEVICE="iPhone SE"
          - RUNTIME="iOS 10.2" DEVICE="iPhone 7 Plus"
          - RUNTIME="iOS 12.4" DEVICE="iPhone XS Max"
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: 'Select Xcode 12.4'
      run: |
        sudo xcode-select -s /Applications/Xcode_12.4.app
        xcodebuild -version -sdk
        xcrun simctl list
    - name: "Build and Test"
      run: |
        ${{ matrix.env }}
        DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        DESTINATION_ID=$(xcrun simctl create Travis $DEVICE_ID $RUNTIME_ID)
        xcrun simctl boot $DESTINATION_ID
        set -o pipefail
        xcodebuild test -workspace "OneTimePassword.xcworkspace" -scheme "OneTimePassword (iOS)" -destination "id=$DESTINATION_ID" | xcpretty -c

  xcode-12-4-swift-5-ios:
    name: "Xcode 12.4, Swift 5, iOS"
    runs-on: macOS-10.15
    strategy:
      matrix:
        destination:
          - name=iPhone 5,OS=10.1
          - name=iPhone XÊ€,OS=12.4
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: 'Select Xcode 12.4'
      run: |
        sudo xcode-select -s /Applications/Xcode_12.4.app
        xcodebuild -version -sdk
        xcrun simctl list
    - name: "Build and Test"
      run: |
        set -o pipefail
        xcodebuild test SWIFT_VERSION=5 -workspace "OneTimePassword.xcworkspace" -scheme "OneTimePassword (iOS)" -destination "platform=iOS Simulator,${{ matrix.destination }}" | xcpretty -c
